# e.g.
# ---
# - ML_EVA_MI:
#    data_filepath: data/xxx.csv
#    model_filepath: model/xxx.xxx
#    stats_filepath: stats/xxx.csv
#    cov_filepath: cov/xxx.csv
---
general:
    plant_name: '台麗朗'
    event_unit: 

web_api_setting:
    host: 10.153.199.221
    port: 80
    docker_port: 10008

lims_setting:
    history_linked_server: 
    history_view: 

sql_connect:
    rtpms: mssql+pyodbc://sa:`1qaz2wsx@10.153.196.180:1433/master?driver=MSSQL
    lims: mssql+pyodbc://sa:`1qaz2wsx@10.110.196.60:1433/master?driver=MSSQL
    fpc_ft: mssql+pyodbc://sa:`1qaz2wsx@10.153.196.59:1433/teller_test?driver=MSSQL

predict_items:
    TLL_viscosity:
        device: "黏度"
        note: "XGBOOST"
        data_name: TRL.csv
        data_target:
        algo_name: [TRL_xgb.sav]
        algo_r2: [0.87]
        algo_dir_path: models/
        data_dir_path: data/
        prep_dir_path: prep/
        prep_name: [TRL_scaler.sav]
        scaler: TRL_scaler.sav
        confidence: True
        confidence_bounds: [0.5, 0.7]
        predict_sleep_seconds: 900
        revise: False
        revise_minutes_low: -60
        revise_minutes_high: 60
        revise_sample_times: 2
        threshold: 0.3
        target_source: rtpms
        sample_point:
        sample_item:
        grade_list: 
        tags: [JPC1-VSMA162A3.PV]
    TRL_viscosity_Conv1D:
        device: "黏度"
        note: "Conv1D"
        data_name: small_TRL_TS_0719.csv
        data_target:
        algo_name: [new_ConV.h5]
        algo_r2: [0.87]
        algo_dir_path: models/
        data_dir_path: data/
        prep_dir_path: prep/
        prep_name: [TRL_X_scaler_0719.sav]
        scaler: TRL_X_scaler_0719.sav
        confidence: True
        confidence_bounds: [0.5, 0.7]
        predict_sleep_seconds: 900
        revise: False
        revise_minutes_low: -60
        revise_minutes_high: 60
        revise_sample_times: 2
        threshold: 0.3
        target_source: rtpms
        sample_point:
        sample_item:
        grade_list: 
        tags: [JPC1-VSMA162A3.PV]
